### PR TITLE
Add support Time and Input layout for MacOS

### PR DESCRIPTION
**Pull request by suhanovv**
I've added basic support of MacOs. Check it please, because I'm not a rust developer, I've just read documentation))
And perhaps I've made mistakes in github workflows, because I've never configured it before

Whats included:
Time - works out of the box
Keyboard Layout - Implemented

I've tested it on my m3 macbook - It's work

### CODE REVIEW

**Comment by zzeneg** [comment]
I have to ability to verify it works so I'm just going to merge it :)

**Comment by kellstromtubene860** [comment]
Could you please also add a macos version in the latest release?

**Comment by zzeneg** [comment]
@kellstromtubene860 macos artifact added, I had to move everything in archives to avoid name conflicts. Let me know if it's ok.

**Comment by kellstromtubene860** [comment]
Thank you! It's fine now

**Pull request merged**
